### ISSUE TITLE
Question about IoU Metrics error

### ISSUE THREAD

**Issue by Jinyang228** [Layout-Generation/layout-generation#11]
Hi, sorry to bother you. The max value of metrics IoU is 1 and the mix is 0. The result shows 2700 and all of the results  rather than 1.

**Comment by yashjain7856** [comment]
Hi notablefire, 
The data is normalized w.r.t. the original publaynet dataset. All the values for original dataset are considered to be 1 and others are scaled accordingly.

The value of iou for original dataset would be very low because there is almost no overlap in the boxes (say 0.001). Now if some dataset has iou of 0.5, we have shown its iou as 0.5/0.001 = 500 and the iou of original dataset as 0.001/0.001 = 1. 


The normzalizing is done in the second last block in these lines. 
`
#normalizing the lists w.r.t the original data
overlist/=overlist[0]
ioulist/=ioulist[0]
alignlist/=alignlist[0]
`

**Comment by Jinyang228** [comment]
> Hi notablefire, The data is normalized w.r.t. the original publaynet dataset. All the values for original dataset are considered to be 1 and others are scaled accordingly.
> 
> The value of iou for original dataset would be very low because there is almost no overlap in the boxes (say 0.001). Now if some dataset has iou of 0.5, we have shown its iou as 0.5/0.001 = 500 and the iou of original dataset as 0.001/0.001 = 1.
> 
> The normzalizing is done in the second last block in these lines. `#normalizing the lists w.r.t the original data overlist/=overlist[0] ioulist/=ioulist[0] alignlist/=alignlist[0]`

Thanks a lot.
