### ISSUE TITLE
rico_data = np.load(root+'Data/rico_new.npy')

### ISSUE THREAD

**Issue by notablefire** [Layout-Generation/layout-generation#9]
Excuse me. Thanks for you sharing codes, very nice!
For Layout Transformer,  I wanna ask you how to find the rico_new.npy dataset, thank you very much!

For LayoutVAE, DATA_PATH link https://developer.ibm.com/exchanges/data/all/publaynet/ shows publaynet dataset has 96 GB, is there any other dataset for training, thank you very much!

For Metrics, 
Transformer_res=np.load(root+"trans.npy")
VAE_res = np.load(root+"VAE_res.npy")
GAN_res = np.load(root+"GAN_res.npy")
how to get those npy dataset. 

Sorry to bother you. Thanks for your sharing code!! Thanks a million.

**Comment by tushar-jain01** [comment]
hello notablefire,
For LayoutVAE, There is no need for using FULL data set with images. because all we need is labels. so you can use this [Link](https://dax-cdn.cdn.appdomain.cloud/dax-publaynet/1.0.0/labels.tar.gz)
 . This is a dataset that contains labels and then you can process the JSON file into required format.

**Comment by tushar-jain01** [comment]
Also Please check this out [#issue4](https://github.com/Layout-Generation/layout-generation/issues/4#issuecomment-954498167)
